services:
  kite-sessions:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - /home/sfroeber/GitHub/kite-sessions-to-strava:/home/dev/workspace:rw,z
